import type { DashboardSnapshot, GoalTask } from "@/types/app";
import type { Json, Tables } from "@/types/database";

const now = new Date();

function ago(hours: number) {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

const profile: Tables<"profiles"> = {
  id: "demo-user-1",
  nickname: "Food Goblin",
  emoji_identity: "Food Goblin 🍜",
  avatar_key: "peach-cat",
  theme_preference: "rosewater",
  bio: "Professional snack scout and cozy plan collector.",
  active_couple_id: "demo-couple-1",
  last_seen_at: ago(0.2),
  created_at: ago(240),
  updated_at: ago(0.2),
};

const partner: Tables<"profiles"> = {
  id: "demo-user-2",
  nickname: "Movie Monster",
  emoji_identity: "Movie Monster 🍿",
  avatar_key: "cosmic-bunny",
  theme_preference: "rosewater",
  bio: "Will always vote for dessert and one more episode.",
  active_couple_id: "demo-couple-1",
  last_seen_at: ago(0.4),
  created_at: ago(240),
  updated_at: ago(0.4),
};

const couple: Tables<"couples"> = {
  id: "demo-couple-1",
  created_by: profile.id,
  partner_one_id: profile.id,
  partner_two_id: partner.id,
  invite_code: "USV123",
  status: "active",
  paired_at: ago(200),
  unlinked_at: null,
  created_at: ago(210),
  updated_at: ago(0.5),
};

const ideas: Tables<"ideas">[] = [
  {
    id: "idea-1",
    couple_id: couple.id,
    created_by: profile.id,
    title: "Late-night dumpling crawl",
    description: "Three tiny dumpling spots, one ridiculous rating sheet.",
    category: "food",
    emoji: "🥟",
    tags: ["cozy", "spicy", "night"],
    image_url: null,
    priority_weight: 5,
    status: "shortlisted",
    created_at: ago(14),
    updated_at: ago(10),
  },
  {
    id: "idea-2",
    couple_id: couple.id,
    created_by: partner.id,
    title: "Blanket fort movie marathon",
    description: "Two comfort movies, one wild card, extra caramel popcorn.",
    category: "movies",
    emoji: "🎬",
    tags: ["home", "comfort", "rainy-day"],
    image_url: null,
    priority_weight: 4,
    status: "pending",
    created_at: ago(20),
    updated_at: ago(20),
  },
  {
    id: "idea-3",
    couple_id: couple.id,
    created_by: profile.id,
    title: "Sunset chai walk",
    description: "No phones, just music and hot chai in paper cups.",
    category: "date_plans",
    emoji: "☕",
    tags: ["soft", "cozy"],
    image_url: null,
    priority_weight: 5,
    status: "completed",
    created_at: ago(70),
    updated_at: ago(6),
  },
  {
    id: "idea-4",
    couple_id: couple.id,
    created_by: partner.id,
    title: "Mystery dessert quest",
    description: "Pick a neighborhood and let sugar decide the rest.",
    category: "activities",
    emoji: "🍰",
    tags: ["sweet", "chaos"],
    image_url: null,
    priority_weight: 3,
    status: "pending",
    created_at: ago(30),
    updated_at: ago(30),
  },
];

const goals: GoalTask[] = [
  {
    id: "goal-1",
    couple_id: couple.id,
    created_by: profile.id,
    title: "Pick dinner before everyone gets too hungry",
    goal_date: now.toISOString().slice(0, 10),
    completed_at: null,
    completed_by: null,
    created_at: ago(3),
    updated_at: ago(3),
  },
  {
    id: "goal-2",
    couple_id: couple.id,
    created_by: partner.id,
    title: "Add one tiny memory from this week",
    goal_date: now.toISOString().slice(0, 10),
    completed_at: null,
    completed_by: null,
    created_at: ago(2.4),
    updated_at: ago(2.4),
  },
  {
    id: "goal-3",
    couple_id: couple.id,
    created_by: partner.id,
    title: "Send the invite code to the group",
    goal_date: now.toISOString().slice(0, 10),
    completed_at: ago(1.1),
    completed_by: profile.id,
    created_at: ago(5),
    updated_at: ago(1.1),
  },
];

const votes: Tables<"votes">[] = [
  {
    id: "vote-1",
    couple_id: couple.id,
    created_by: partner.id,
    idea_id: null,
    prompt: "Tonight: dumplings or tacos?",
    mode: "vibe",
    status: "active",
    options: ["Hell yes", "Maybe", "Nope"],
    closes_at: null,
    created_at: ago(4),
    updated_at: ago(4),
  },
  {
    id: "vote-2",
    couple_id: couple.id,
    created_by: profile.id,
    idea_id: "idea-3",
    prompt: "How cute was the chai walk?",
    mode: "rating",
    status: "closed",
    options: ["1", "2", "3", "4", "5"],
    closes_at: null,
    created_at: ago(8),
    updated_at: ago(6),
  },
];

const voteResponses: Tables<"vote_responses">[] = [
  {
    id: "vote-response-1",
    couple_id: couple.id,
    vote_id: "vote-1",
    user_id: profile.id,
    response_value: "Hell yes",
    rating_value: null,
    emoji_value: null,
    comment: "Need noodles immediately.",
    created_at: ago(3.9),
    updated_at: ago(3.9),
  },
  {
    id: "vote-response-2",
    couple_id: couple.id,
    vote_id: "vote-1",
    user_id: partner.id,
    response_value: "Maybe",
    rating_value: null,
    emoji_value: null,
    comment: null,
    created_at: ago(3.8),
    updated_at: ago(3.8),
  },
  {
    id: "vote-response-3",
    couple_id: couple.id,
    vote_id: "vote-2",
    user_id: profile.id,
    response_value: null,
    rating_value: 5,
    emoji_value: null,
    comment: "Peak cozy",
    created_at: ago(6),
    updated_at: ago(6),
  },
  {
    id: "vote-response-4",
    couple_id: couple.id,
    vote_id: "vote-2",
    user_id: partner.id,
    response_value: null,
    rating_value: 5,
    emoji_value: null,
    comment: "Would repeat instantly",
    created_at: ago(6),
    updated_at: ago(6),
  },
];

const messages: Tables<"messages">[] = [
  {
    id: "message-1",
    couple_id: couple.id,
    sender_id: partner.id,
    content: "I found a dumpling place with soup buns the size of tiny moons.",
    read_by: [profile.id, partner.id],
    reaction_map: {
      "💗": [profile.id],
    } satisfies Json,
    created_at: ago(5),
    updated_at: ago(5),
  },
  {
    id: "message-2",
    couple_id: couple.id,
    sender_id: profile.id,
    content: "That sounds illegal in the best possible way.",
    read_by: [profile.id, partner.id],
    reaction_map: {
      "😂": [partner.id],
    } satisfies Json,
    created_at: ago(4.8),
    updated_at: ago(4.7),
  },
  {
    id: "message-3",
    couple_id: couple.id,
    sender_id: partner.id,
    content: "Also voting for blanket fort energy later if we survive dinner.",
    read_by: [profile.id, partner.id],
    reaction_map: {} satisfies Json,
    created_at: ago(4.5),
    updated_at: ago(4.5),
  },
];

const moods: Tables<"moods">[] = [
  {
    id: "mood-1",
    couple_id: couple.id,
    user_id: profile.id,
    mood: "hungry",
    note: "Need something warm and dramatic.",
    created_at: ago(2),
  },
  {
    id: "mood-2",
    couple_id: couple.id,
    user_id: partner.id,
    mood: "hungry",
    note: "Would absolutely chase dumplings across the city.",
    created_at: ago(1.5),
  },
];

const memories: Tables<"memories">[] = [
  {
    id: "memory-1",
    couple_id: couple.id,
    created_by: profile.id,
    related_idea_id: "idea-3",
    related_vote_id: null,
    title: "Sunset chai walk",
    description: "Tiny paper cups, golden sky, and exactly zero hurry.",
    memory_type: "memory",
    celebration_level: 4,
    cover_url: null,
    metadata: {} satisfies Json,
    occurred_at: ago(6),
    created_at: ago(5.8),
  },
  {
    id: "memory-2",
    couple_id: couple.id,
    created_by: partner.id,
    related_idea_id: null,
    related_vote_id: null,
    title: "Your universe connected",
    description: "The moment the private little world officially became yours.",
    memory_type: "milestone",
    celebration_level: 5,
    cover_url: null,
    metadata: {
      milestone: "paired",
    } satisfies Json,
    occurred_at: ago(200),
    created_at: ago(200),
  },
];

const notifications: Tables<"notifications">[] = [
  {
    id: "notification-1",
    user_id: profile.id,
    couple_id: couple.id,
    actor_id: partner.id,
    type: "idea_added",
    title: "something new landed 👀",
    body: 'Movie Monster added "Blanket fort movie marathon".',
    payload: {} satisfies Json,
    read_at: null,
    created_at: ago(20),
  },
  {
    id: "notification-2",
    user_id: profile.id,
    couple_id: couple.id,
    actor_id: partner.id,
    type: "vote_started",
    title: "vote started 🎉",
    body: "Tonight: dumplings or tacos?",
    payload: {} satisfies Json,
    read_at: ago(3.5),
    created_at: ago(4),
  },
];

const gameSessions: Tables<"game_sessions">[] = [
  {
    id: "game-session-1",
    couple_id: couple.id,
    created_by: profile.id,
    game_type: "spin_the_wheel",
    prompt: "Caught 11 peaches in 19s",
    state: {
      label: "Peach Catch",
      score: 22,
      catches: 11,
      misses: 1,
      durationMs: 19000,
    } satisfies Json,
    winner_id: profile.id,
    completed_at: ago(16),
    created_at: ago(16),
    updated_at: ago(16),
  },
  {
    id: "game-session-2",
    couple_id: couple.id,
    created_by: partner.id,
    game_type: "emoji_guessing",
    prompt: "Popped 17 bubbles with a 5x combo",
    state: {
      label: "Bubble Pop",
      score: 28,
      popped: 17,
      combo: 5,
      durationMs: 18000,
    } satisfies Json,
    winner_id: partner.id,
    completed_at: ago(10),
    created_at: ago(10),
    updated_at: ago(10),
  },
  {
    id: "game-session-3",
    couple_id: couple.id,
    created_by: profile.id,
    game_type: "partner_quiz",
    prompt: "Matched 6 pairs in 14 moves",
    state: {
      label: "Memory Match",
      score: 39,
      matchedPairs: 6,
      moves: 14,
      durationMs: 24000,
    } satisfies Json,
    winner_id: profile.id,
    completed_at: ago(6),
    created_at: ago(6),
    updated_at: ago(6),
  },
];

export function createDemoSnapshot(): DashboardSnapshot {
  return {
    profile: { ...profile },
    members: [{ ...profile }, { ...partner }],
    partner: { ...partner },
    couple: { ...couple },
    ideas: ideas.map((idea) => ({ ...idea, tags: [...idea.tags] })),
    goals: goals.map((goal) => ({ ...goal })),
    votes: votes.map((vote) => ({ ...vote })),
    voteResponses: voteResponses.map((response) => ({ ...response })),
    messages: messages.map((message) => ({
      ...message,
      read_by: [...message.read_by],
      reaction_map: JSON.parse(JSON.stringify(message.reaction_map)) as Json,
    })),
    moods: moods.map((mood) => ({ ...mood })),
    memories: memories.map((memory) => ({ ...memory })),
    notifications: notifications.map((notification) => ({ ...notification })),
    gameSessions: gameSessions.map((session) => ({ ...session })),
  };
}
